sonar.projectKey=joa851_playerhub-backend-springboot
sonar.organization=joa851
sonar.host.url=https://sonarcloud.io

# 4 microservicios como módulos del mismo proyecto Sonar
sonar.modules=configserver,eurekaserver,player,comments

# --- configserver ---
configserver.sonar.sources=src/main/java
configserver.sonar.tests=src/test/java
configserver.sonar.java.binaries=target/classes
configserver.sonar.java.test.binaries=target/test-classes
configserver.sonar.coverage.jacoco.xmlReportPaths=target/site/jacoco/jacoco.xml
configserver.sonar.junit.reportPaths=target/surefire-reports

# --- eurekaserver ---
eurekaserver.sonar.sources=src/main/java
eurekaserver.sonar.tests=src/test/java
eurekaserver.sonar.java.binaries=target/classes
eurekaserver.sonar.java.test.binaries=target/test-classes
eurekaserver.sonar.coverage.jacoco.xmlReportPaths=target/site/jacoco/jacoco.xml
eurekaserver.sonar.junit.reportPaths=target/surefire-reports

# --- player ---
player.sonar.sources=src/main/java
player.sonar.tests=src/test/java
player.sonar.java.binaries=target/classes
player.sonar.java.test.binaries=target/test-classes
player.sonar.coverage.jacoco.xmlReportPaths=target/site/jacoco/jacoco.xml
player.sonar.junit.reportPaths=target/surefire-reports

# --- comments ---
comments.sonar.sources=src/main/java
comments.sonar.tests=src/test/java
comments.sonar.java.binaries=target/classes
comments.sonar.java.test.binaries=target/test-classes
comments.sonar.coverage.jacoco.xmlReportPaths=target/site/jacoco/jacoco.xml
comments.sonar.junit.reportPaths=target/surefire-reports

# Exclusiones globales
sonar.exclusions=**/target/**,**/.mvn/**,**/Dockerfile,**/mvnw,**/mvnw.cmd
