spring.application.name=configserver

server.port=${PORT:8888}
spring.cloud.config.server.git.uri=${SPRING_CLOUD_CONFIG_SERVER_GIT_URI:https://github.com/joa851/playerhub-backend-springboot-config}
spring.cloud.config.server.git.default-label=main
